# Generated by Django 3.2 on 2022-03-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_aimodel_failed_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
